use_frameworks!

target 'BStompClient_Example' do
  pod 'BStompClient', :path => '../'

  target 'BStompClient_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
